spring:

  devtools:
    add-properties: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/sass?createDatabaseIfNotExist=true
    username: root
    password: 123456
    maxPoolSize: 10
    minIdle: 10
    connectionTimeout: 20000
    idleTimeout: 300000
    poolName: sass-connection-pool
  liquibase:
    drop-first: true
