spring:
  devtools:
    add-properties: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/sass?createDatabaseIfNotExist=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 3
  liquibase:
    drop-first: false